// <auto-generated />
using System;
using Financ.Infra.Data.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Financ.Infra.Data.Migrations
{
    [DbContext(typeof(AppContextoData))]
    partial class AppContextoDataModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("Financ.Domain.Entidades.Contas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CreditoLimite")
                        .HasColumnType("REAL");

                    b.Property<int>("DiaFechamento")
                        .HasMaxLength(16)
                        .HasPrecision(2)
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiaVencimento")
                        .HasMaxLength(12)
                        .HasPrecision(2)
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DthrReg")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoConta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("fnc_contas", (string)null);
                });

            modelBuilder.Entity("Financ.Domain.Entidades.ContasUsuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Acesso")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DthrReg")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdConta")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdConta");

                    b.ToTable("fnc_contas_usuarios", (string)null);
                });

            modelBuilder.Entity("Financ.Domain.Entidades.ContasUsuarios", b =>
                {
                    b.HasOne("Financ.Domain.Entidades.Contas", "Contas")
                        .WithMany("ContasUsuarios")
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contas");
                });

            modelBuilder.Entity("Financ.Domain.Entidades.Contas", b =>
                {
                    b.Navigation("ContasUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
